# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [6]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [8]:
B = np.arange(1, 10).reshape(3, 3) #matrix with numbers 1-9 in 3 rows and 3 cols
C = np.ones((3, 3))*2 #matrix with the number 2 (1*2) in all positions/elements

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [149]:
result_subtraction_elementwise = B-C #subtract 2 from each element in matrix B (C contains the number 2)
result_multiply_elementwise = B*C #multiply each element in matrix B with the number 2
result_matrix_multiply = B@C 
print(result_subtraction_elementwise)
print()
print(result_multiply_elementwise)
print()
print(result_matrix_multiply)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [16]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
result_exponentiate_elementwise = np.exp(B)
print("Exponentierad matris:\n", result_exponentiate_elementwise)
print()
min_value = np.min(B)
print("Minsta värdet i matrisen:", min_value)
print()
min_value_row = np.min(B, axis=1)
print("Minsta värdet per rad:", min_value_row)
print()
min_value_col = np.min(B, axis=0)
print("Minsta värdet per kolumn:", min_value_col)
print()
index_min_matrix = np.argmin(B)
print("Index för minsta värdet i matrisen:", index_min_matrix)
print()
index_min_per_row = np.argmin(B, axis=1)
print("Index för minsta värdet per rad:", index_min_per_row)
print()
total_sum = np.sum(B)
print("Summan av alla element:", total_sum)
print()
mean_value_col = np.mean(B, axis=0)
print("Medelvärde per kolumn:", mean_value_col)
print()
median_value_col = np.median(B, axis=0)
print("Median per kolumn:", median_value_col)

Exponentierad matris:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minsta värdet i matrisen: 1

Minsta värdet per rad: [1 4 7]

Minsta värdet per kolumn: [1 2 3]

Index för minsta värdet i matrisen: 0

Index för minsta värdet per rad: [0 0 0]

Summan av alla element: 45

Medelvärde per kolumn: [4. 5. 6.]

Median per kolumn: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [30]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [32]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [60]:
# When providing only one index when the matrix have two axes (rows and cols), numpy will select the first axes (the row) correspondning to the index given (i.e second row when index 1) and return all column values in that row as an 1D-array.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [40]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [42]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [48]:
#Use the flat-method to iterate a multidimentional array elementwise over all elements
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [151]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# a = np.arange(30) creates a 1D array with numbers from 0 to 29 i.e. a vector/single row with 30 elements

In [50]:
# The .reshape() function changes the dimensions of the array without changing its data. The array b will have 3 axes i.e. a 3D array
# The -1 tells NumPy to automatically calculate the correct size for that axis based on the total number of elements in the array.
# 30 elements in vector a, 2*3 = 6 elements --> calculates third dimension = 30/6 = 5


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [52]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [54]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [153]:
A = np.arange(1, 5).reshape(2,2)
print(A)
print()
b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]

[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [160]:
def add_mult_matrices(matrix1, matrix2, operation):
    # Check that both are numpy-arrays
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise TypeError("Both inputs must be of type numpy.ndarray.")
    
    # Check that the operation is valid
    if operation not in ('add', 'multiply', 'subtract'):
        raise ValueError("Operation must be either 'add' or 'multiply'.")
    
    # Addition
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("For addition, matrices must have the same size.")
        return matrix1 + matrix2
        
    # Multiply
    elif operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("For multiplication, number of columns in the first matrix must equal number of rows in the second.")
        return matrix1 @ matrix2  # eller np.matmul(matrix1, matrix2)


In [180]:
my_matrix1 = np.array([[1, 2], [3, 4]])
my_matrix2 = np.array([[5, 6],[7, 8]])

print("Test of addition of my matrices:")
print(add_mult_matrices(my_matrix1, my_matrix2, 'add'))
print()
print("Test of multiplication of my matrices:")
print(add_mult_matrices(my_matrix1, my_matrix2, 'multiply'))

Test of addition of my matrices:
[[ 6  8]
 [10 12]]

Test of multiplication of my matrices:
[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [198]:
# 10.1.1
# x = (4,3)

# a) vektorn x har dimension 1x2
x = np.array([[4, 3]])
print("a) Dimension", np.shape(x))




a) Dimension (1, 2)


In [78]:
# b)
# 5x = (5*4, 5*3) = (20, 15)
b = 5*x
print("b) 5x = ", b)



b) 5x =  [[20 15]]


In [80]:
# c)
# 3x = (3*4, 3*3) = (12, 9)
c = 3*x
print("c) 3x = ", c)


c) 3x =  [[12  9]]


In [84]:
# d)
# 5x + 3x = (20+12), (15+9) = (32, 24)
d = b+c
print("d) 5x + 3x = ", d)


d) 5x + 3x =  [[32 24]]


In [184]:
# e)
# 8x= (8*4, 8*3) = (32, 24)
e = 8*x
print("e) 8x = ", e)


e) 8x =  [[32 24]]


In [90]:
# f)
# 4x - x = (4*4, 4*3) - (4,3)= (16, 12) - (4,3) = (12,9)
f = 4*x - x
print("f) 4x - x = ", f)


f) 4x - x =  [[12  9]]


In [200]:
# g) Ny dimension efter transpose är 2x1
transposed_matrix = x.T
g = transposed_matrix
print(g)
print("g) Ny dimension efter transpose är ", np.shape(g))


[[4]
 [3]]
g) Ny dimension efter transpose är  (2, 1)


In [102]:
# h)  x + x⊤ är inte definierat eftersom x är en 1×2 vektor och x⊤ är en 2×1 vektor.


In [112]:
# i) 
# ||x|| normen av x=(4,3) dvs längden på vektorn
norm = np.linalg.norm(x)
print("i) ||x|| = ", norm)


i) ||x|| =  5.0


In [210]:
# 10.1.2
# v = (3,7,0,11)
# a) 
v = np.array([[3],[7],[0],[11]])
#print(v)
print("a) Dimension", v.shape)



a) Dimension (4, 1)


In [208]:
# b) 
b = 2*v
print("b) 2v = ", b)



b) 2v =  [[ 6]
 [14]
 [ 0]
 [22]]


In [212]:
# c) 
c = 5*v + 2*v
print("b) 5v * 2v = ", c)



b) 5v * 2v =  [[21]
 [49]
 [ 0]
 [77]]


In [220]:
# d)
d = 4*v - 2*v
print("b) 4v - 2v = ", d)



b) 4v - 2v =  [[ 6]
 [14]
 [ 0]
 [22]]


In [222]:
# e
# Ny dimension efter transpose är 1x4
transposed_matrix = v.T
e = transposed_matrix
print(e)
print("e) Ny dimension efter transpose är ", np.shape(e))


[[ 3  7  0 11]]
e) Ny dimension efter transpose är  (1, 4)


In [224]:
# f)
# ||v|| normen av v = (3,7,0,11) dvs längden på vektorn från origo
norm = np.linalg.norm(v)
print("f) ||v|| = ", norm)



f) ||v|| =  13.379088160259652


In [228]:
# 10.1.3
#a)
v1 = (4,3,1,5)
v2 = (2,3,1,1)
normv1 = np.linalg.norm(v1)
print("a) ||v1|| = ", normv1)



a) ||v1|| =  7.14142842854285


In [238]:
# b)
normv2 = np.linalg.norm(v2)
calc = normv1 - normv2
print("b) ||v1-v2|| = ", calc)



b) ||v1-v2|| =  3.2684450823354334


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [308]:
# 10.2.1
A = np.array([[2, 1, -1],
              [1, -1, 1]])
B = np.array([[4, -2, 1],
              [2, -4, -2]])
C = np.array([[1, 2],
              [2, 1]])
D = np.array([[3, 4],
              [4, 3]])
E = np.array([[1],
              [2]])
I = np.array([[1, 0],
              [0, 1]])


In [328]:
# a
# 2A
a = 2*A
print("a) 2A = ")
print(a)

a) 2A = 
[[ 4  6  8]
 [10  8  2]]


In [330]:
# b
# B - 2A
b = B-a
print("b) B - 2A = ")
print(b)

b) B - 2A = 
[[  0  -8  -7]
 [ -8 -12  -4]]


In [332]:
# c
# 3C - 2E
print("C dimension: ", C.shape)
print("E dimension: ", E.shape)
print("Not defined because the matrices do not have the same number of columns")

C dimension:  (2, 2)
E dimension:  (2, 1)
Not defined because the matrices do not have the same number of columns


In [334]:
# d
# 2D - 3C
two_d = 2*D
three_c = 3*C
d = two_d - three_c
print("a) 2D - 3C = ")
print(d)

a) 2D - 3C = 
[[3 2]
 [2 3]]


In [336]:
# e
# D Transposed + 2D
transposed_matrix_D = D.T
e = transposed_matrix_D + two_d
print("D Transposed + 2D = ")
print(e)

D Transposed + 2D = 
[[ 9 12]
 [12  9]]


In [338]:
# f
# 2C transposed - 2D Transposed
transposed_matrix_C = C.T
f = 2*transposed_matrix_C - 2*transposed_matrix_D
print("2*C Transposed - 2*D Transposed = ")
print(f)

2*C Transposed - 2*D Transposed = 
[[-4 -4]
 [-4 -4]]


In [340]:
# g
# A transposed - B
transposed_matrix_A = A.T
print("A transposed dimension: ", transposed_matrix_A.shape)
print("B dimension: ", B.shape)
print("Not defined because the matrices do not have the same number of columns and rows when matrix A have been transposed")

A transposed dimension:  (3, 2)
B dimension:  (2, 3)
Not defined because the matrices do not have the same number of columns and rows when matrix A have been transposed


In [350]:
# h
# AC
print("A dimension: ", A.shape)
print("C dimension: ", C.shape)
print("Not defined because the matrices do not have the same number of columns")

A dimension:  (2, 3)
C dimension:  (2, 2)
Not defined because the matrices do not have the same number of columns


In [342]:
# i
# CD
i = C@D
print("CD =")
print(i)

CD =
[[11 10]
 [10 11]]


In [352]:
# j
# CB
j = C@B
print("CB =")
print(j)

CB =
[[  8 -10  -3]
 [ 10  -8   0]]


In [356]:
# k
# CI
k = C@I
print("CI =")
print(k)

CI =
[[1 2]
 [2 1]]


In [360]:
# l
# A * B transposed
transposed_matrix_B = B.T
l = A@transposed_matrix_B
print("A * B transposed =")
print(l)

A * B transposed =
[[  6 -16]
 [ 13  -8]]


In [362]:
# 10.2.2
A = np.array([[2, 3, 4],
              [5, 4, 1]])
print(A)
print()
transposed_matrix_A = A.T
result = A@transposed_matrix_A
print("A * A transposed =")
print(result)

[[2 3 4]
 [5 4 1]]

A * A transposed =
[[29 26]
 [26 42]]


In [366]:
# 10.2.3
A = np.array([[1, 2],
              [2, 4]])
B = np.array([[2, 1],
              [1, 3]])
C = np.array([[4, 3],
              [0, 2]])

In [378]:
# AB = AC  B != C
A = np.array([[1, 2],
              [2, 4]])
B = np.array([[2, 1],
              [1, 3]])
C = np.array([[4, 3],
              [0, 2]])

AB = A@B
AC = A@C
print("AB = ")
print(AB)
print("AC = ")
print(AC)
print("B = ")
print(B)
print("C = ")
print(C)

AB = 
[[ 4  7]
 [ 8 14]]
AC = 
[[ 4  7]
 [ 8 14]]
B = 
[[2 1]
 [1 3]]
C = 
[[4 3]
 [0 2]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [388]:
v1 = np.arange(4)
v2 = v1[-2:] # Creates a view, not a copy i.e. v2 points at the same data as v1.
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [390]:
# The base attribute is used to check the base of the array, i.e. if it is a copy of another array or not.
# The base attribute returns None if it is not a copy (it is the original)
# The base attribute returns the array if it is a view of another array, i.e. it is a view
print(v1.base) # → None (v1 is not a copy, it is the original)
print(v2.base) # → array([...]) (v2 is a view of v1)

None
[0 1 2 3]


In [392]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
